create extension if not exists pgcrypto;

create table if not exists departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text
);

create table if not exists equipments (
  id bigint generated by default as identity primary key,
  name text not null,
  inventory_code text,
  type text not null,
  status text not null,
  user_assigned text,
  specs jsonb default '{}'::jsonb,
  department_id bigint references departments(id) on delete set null
);

alter table equipments add column if not exists inventory_code text;

create table if not exists it_logs (
  id bigint generated by default as identity primary key,
  date timestamptz not null default now(),
  it_personnel text not null,
  description text not null,
  status text not null,
  equipment_id bigint references equipments(id) on delete set null,
  department_id bigint references departments(id) on delete set null
);

alter table departments enable row level security;
alter table equipments enable row level security;
alter table it_logs enable row level security;

drop policy if exists "public read departments" on departments;
drop policy if exists "public write departments" on departments;
drop policy if exists "public read equipments" on equipments;
drop policy if exists "public write equipments" on equipments;
drop policy if exists "public read logs" on it_logs;
drop policy if exists "public write logs" on it_logs;

create policy "public read departments" on departments for select using (true);
create policy "public write departments" on departments for insert with check (true);
create policy "public write departments update" on departments for update using (true) with check (true);
create policy "public write departments delete" on departments for delete using (true);

create policy "public read equipments" on equipments for select using (true);
create policy "public write equipments" on equipments for insert with check (true);
create policy "public write equipments update" on equipments for update using (true) with check (true);
create policy "public write equipments delete" on equipments for delete using (true);

create policy "public read logs" on it_logs for select using (true);
create policy "public write logs" on it_logs for insert with check (true);
create policy "public write logs update" on it_logs for update using (true) with check (true);
create policy "public write logs delete" on it_logs for delete using (true);
